window.katexConfig = {
    macros: {
      '\\T': '\\top',
      '\\B': '\\bot',
      '\\OR': '\\lor',
      '\\AND': '\\land',
      '\\IF': '\\leftarrow',
      '\\THEN': '\\rightarrow',
      '\\EQ': '\\leftrightarrow',
      '\\satisfy': '\\vDash',
      '\\notsatisfy': '\\nvDash',
      '\\crit': '\\neg H',
      '\\so': '\\rightsquigarrow',
      '\\img': '\\imageof',
      '\\set': '\\{#1\\}\\{s,e,t\\}',
      '\\Set': '\\{#1\\}\\{S,e,t\\}',
      '\\txt': '\\texttt{#1}',
      '\\R': '{\\color{red}{#1}}',
      '\\G': '{\\color{green}{#1}}',
      '\\B': '{\\color{blue}{#1}}',
      '\\P': '{\\color{deeppink}{#1}}',
      '\\V': '{\\color{darkviolet}{#1}}',
      '\\red': '{\\color{red}{\\texttt{#1}}}',
      '\\green': '{\\color{green}{\\texttt{#1}}}',
      '\\blue': '{\\color{blue}{\\texttt{#1}}}',
      '\\pink': '{\\color{deeppink}{\\texttt{#1}}}',
      '\\violet': '{\\color{darkviolet}{\\texttt{#1}}}',
      '\\Rtxt': '{\\color{red}{\\texttt{#1}}}',
      '\\Gtxt': '{\\color{green}{\\texttt{#1}}}',
      '\\Btxt': '{\\color{blue}{\\texttt{#1}}}',
      '\\Ptxt': '{\\color{deeppink}{\\texttt{#1}}}',
      '\\Vtxt': '{\\color{darkviolet}{\\texttt{#1}}}',
      '\\Rbox': '{\\colorbox{salmon}{$#1$}}',
      '\\Gbox': '{\\colorbox{lightgreen}{$#1$}}',
      '\\Bbox': '{\\colorbox{skyblue}{$#1$}}',
      '\\Pbox': '{\\colorbox{pink}{$#1$}}',
      '\\Vbox': '{\\colorbox{plum}{$#1$}}'
    }
  };
